In [0]:
import torch
import torch.nn as nn
from torch.nn import Linear
import numpy as np
import matplotlib.pyplot as plt

## 1. Linear Regression y = wx + b 구현하기

In [0]:
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

In [0]:
def forward(x):
    y = w*x + b
    return y

In [4]:
x = torch.tensor([[4], [7]])
forward(x)

tensor([[13.],
        [22.]], grad_fn=<AddBackward0>)

## 2. 랜덤 시드를 통해 Linear Regression 만들기 및 tensor 배열 값 넣기 

In [5]:
torch.manual_seed(1)
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [6]:
x = torch.tensor([2.0])
print(model(x))

tensor([0.5891], grad_fn=<AddBackward0>)


In [7]:
x = torch.tensor([[2.0], [4.0], [6.0]])
print(model(x))

tensor([[0.5891],
        [1.6197],
        [2.6502]], grad_fn=<AddmmBackward>)


## 3. 딥러닝을 통한 Linear Regression 구현

In [22]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = torch.optim.SGD([W, b], lr=0.01)

nb_epochs = 4000 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = W * x_train + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # gradient를 0으로 초기화
    # 미분을 통해 얻은 기울기를 0으로 초기화 -> 새 기울기를 구하기 위함
    optimizer.zero_grad()
    # 손실함수를 미분하여 gradient 계산
    # loss.backward() 함수를 통해 W, b에 대한 기울기가 계산 된다.
    cost.backward()
    # W와 b를 업데이트 
    # 경사 하강법 최적화 함수 optimzer의 step 함수를 호출하여 파라미터로 들어간 W, b에서
    # 리턴되는 변수들의 기울기에 학습률 0.01을 곱하여 빼줌으로서 업데이트 수행  
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/4000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/4000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/4000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/4000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/4000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/4000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/4000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/4000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/4000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/4000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/4000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/4000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/4000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/4000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/4000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/4000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/4000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/4000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/4000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/4000 W: 1.997, b: 0.008 Cost: 0.000008